### ISSUE TITLE
Error on attempting to render DevTools

### ISSUE THREAD

**Issue by morgante** [gaearon/redux-devtools#147] opened 2015-10-09 14:55 UTC
When I try to add DevTools to my view, I get this error:

```
Uncaught Error: Invariant Violation: DevToolsWrapper.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

My store configuration looks like this:
```
import { compose, createStore, applyMiddleware } from 'redux';
import thunkMiddleware from 'redux-thunk';
import loggerMiddleware from 'redux-logger';
import rootReducer from '../reducers';
import { devTools, persistState } from 'redux-devtools';

import apiMiddleware from '../api/middleware';

const createStoreWithMiddleware = compose(
    applyMiddleware(
        thunkMiddleware,
        loggerMiddleware,
        apiMiddleware
    ),
    devTools(),
    persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
)(createStore);

export default function configureStore(initialState) {
    const store = createStoreWithMiddleware(rootReducer, initialState);

    if (module.hot) {
        // Enable Webpack hot module replacement for reducers
        module.hot.accept('../reducers', () => {
            const nextRootReducer = require('../reducers');
            store.replaceReducer(nextRootReducer);
        });
    }

    return store;
}
```

And my root component is rendered like this:
```
import { DevTools, DebugPanel, LogMonitor } from 'redux-devtools/lib/react';

const store = configureStore();

function render(Container, domNode) {
    React.render(
        <div>
            <Provider store={store}>
                {() =>
                    <Container />
                }
            </Provider>,
            <DevTools store={store} monitor={LogMonitor} visibleOnLoad={false} />
        </div>,
        domNode
    );
}
```

**Comment by gaearon** [comment] 2015-10-16 23:26
It's hard to say what exactly the issue is, but you can see that both examples in this repo and `real-world` example in `redux` repo run fine, so it's something in your configuration or imports that is wrong. Please provide a project reproducing the problem. I'm closing.

**Closed by gaearon** 2015-10-16 23:26 UTC
