### ISSUE TITLE
Redux Devtools breaks out of devtools container

### ISSUE THREAD

**Issue by wldcordeiro** [gaearon/redux-devtools#374] opened 2017-07-14 19:17 UTC
I've noticed that after a few actions go through the redux devtools end up in a weird visual state where the bottom is cut off.

**Comment by osag-mie** [comment] 2017-08-03 08:37
I can confirm this. This applies to the tab in firefox web developer tools, as well as the standalone popup window of the redux devtools.
Not only is the main panel cut off, but the bottom buttons are pushed out of view as well.

Firefox 54.0
Redux DevTools 2.15.1

**Comment by rudfoss** [comment] 2017-11-15 10:14
I'm seeing the same. Here's a quick screenshot:
![redux-bug](https://user-images.githubusercontent.com/1716298/32830597-fcfadcbe-c9f5-11e7-85ac-7b3947ae2bf1.png)

I tried pushing it back by opening the console, but that has no effect.

**Comment by rikkit** [comment] 2017-11-15 13:37
Seems to be whenever either panel has scrollbars. Because it seems that the amount clipped at the bottom is the same height as the navigation bar at the top, I'd guess at the issue being the max heights of the scrollable areas being set incorrectly and not accounting for the bottom nav.

**Comment by zalmoxisus** [comment] 2018-03-02 15:40
Fixed in version `2.15.2` of the extension. It's available on AMO. Sorry about the delay!

**Closed by zalmoxisus** 2018-03-02 15:40 UTC
