### ISSUE TITLE
dev tools getting an error...Lazy require of extension.binding did not set the binding field

### ISSUE THREAD

**Issue by born2net** [gaearon/redux-devtools#338] opened 2017-02-04 15:38 UTC
dev tools getting an error...Lazy require of extension.binding did not set the binding field 

```
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) Lazy require of extension.binding did not set the binding field
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) extensions::lastError:82: Uncaught TypeError: Cannot convert undefined or null to object{TypeError: Cannot convert undefined or null to object
    at Object.clear (extensions::lastError:82:23)
    at handleResponse (extensions::sendRequest:84:15)
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/pagewrap.bundle.js:1:1}
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) extensions::messaging:9: Uncaught Natives disabled{<stack trace unavailable>}
Uncaught
  (anonymous function)	
```

repo:  https://github.com/born2net/studioweb

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by zalmoxisus** [comment] 2017-02-04 15:49
Online demo would save me some time to debug, but http://ng2.javascriptninja.io redirects to http://secure.digitalsignage.com/boiler/

**Comment by born2net** [comment] 2017-02-04 15:54
yes sorry my signature is confusing.
here is link to repo demo online: https://secure.digitalsignage.com/studioweb/
and source:   https://github.com/born2net/studioweb
but it seems to do it only when I debug in WebStorm :/
see image

![err](https://cloud.githubusercontent.com/assets/5090936/22619691/29d2a720-eaaf-11e6-90fe-0aa58bb04743.PNG)

if I disable the chrome ext dev-tools, no error

**Comment by zalmoxisus** [comment] 2017-02-04 16:06
Well, I don't see much information here. Could you provide some steps to reproduce? Also you can [run the extension in dev mode](https://github.com/zalmoxisus/redux-devtools-extension#1-for-chrome) to get more details. Note that you should clone [the extension's repo(https://github.com/zalmoxisus/redux-devtools-extension), not `redux-devtools`, which are completely different.

**Comment by born2net** [comment] 2017-02-04 16:09
ok will be back later this afternoon and will do

**Comment by zalmoxisus** [comment] 2017-02-05 14:33
I tried running your repo and don't get any problems (though I see you're not using the extension after logging in). Could be a problem with interfering with Webpack's extension. If you'll provide exact steps on how to debug it with Webpack so the exception occurs, I'd look into it.

**Comment by born2net** [comment] 2017-02-05 14:44
if i was a betting man I would bet it is an issue with latest ng-cli (thus Webpack) as I am working closely with the ng-cli team and they are making major changes right now pushing towards last release.
so I believe you are right most likely related to webpack / ng-cli (I am using ng-cli .30 beta)
Here is the new repo (moved) of cli: 
https://www.npmjs.com/package/@angular/cli

regards

Sean

**Comment by born2net** [comment] 2017-02-08 17:17
I tried to compile the dev extension but no luck.
I am still seeing  the issue.
Any chance someone can check with my repo:
https://github.com/born2net/studioweb

Also, I was mistaken and this is not related to ng4, same issue with ng2.
and it makes working with dev-tools really hard because my console is clobbered with error all the time.
see attached image:

![capture](https://cloud.githubusercontent.com/assets/5090936/22748580/5fe22510-eddf-11e6-8e40-57e71c759a7c.PNG)


TX

Sean

**Comment by born2net** [comment] 2017-02-08 17:17
1.

**Comment by zalmoxisus** [comment] 2017-02-08 17:21
Hey Sean,

Once again, please provide detailed steps on what should be done in Webpack to reproduce that.

**Comment by born2net** [comment] 2017-02-08 17:25
Hi,
So I am using angular-cli .30 which is also part of my project when you fork it, just run:
```npm run dev```
and that's it
If you wish I can make a video
TX
Sean

**Comment by zalmoxisus** [comment] 2017-02-08 17:26
Sorry, I meant WebStorm not webpack. Written steps of what should be done in WebStorm would be great.

What was the issue with compiling the extension? It's just `npm i && npm run buld:extension`.

**Comment by born2net** [comment] 2017-02-08 17:29
again I do apologize, my bad, it's not related to WebStorm at all.
It's an issue with redux dev-tool, thus I included a new snapshot showing console error in Chrome dev tools.
sorry for misleading.
reproducing should be real easy, standing by to assist.

**Comment by zalmoxisus** [comment] 2017-02-08 17:45
Well, I tried the repo before and didn't get any exceptions. I synced your last  changes and still don't replicate the issue:

![tyrhdbj2td](https://cloud.githubusercontent.com/assets/7957859/22749726/0188d51a-ee37-11e6-9b66-084ad2c9390f.gif)

**Comment by born2net** [comment] 2017-02-08 17:55
so odd :(
please see this:
https://dl.dropboxusercontent.com/u/93017334/ErrDevTools.mp4
any ideas? something I can check?

**Comment by born2net** [comment] 2017-02-08 18:00
:( very odd, can you please check this video: 

https://dl.dropboxusercontent.com/u/93017334/ReduxErr.mp4

TX
Sean

**Comment by zalmoxisus** [comment] 2017-02-08 18:42
As I see in the video, it's still inspected by Webstorm extension. Could you try it without WebStorm?

I didn't use Websorm IDE debugging, if you can provide some steps, I'll check that.

**Comment by born2net** [comment] 2017-02-08 18:50
you are absolutely right, I disabled the WebStorm debug extension and now, no more errors.
so WebStorm and Devtools are not liking each other.
What can I provide to help resolve the issue?
TX

Sean

**Comment by zalmoxisus** [comment] 2017-02-08 19:00
WebStorm is trying to inspect the Redux Extension's script, which it shouldn't do. As told, I'm not an expert in WebStorm. If you provide some steps on how to run debugging in the IDE as you do, I'd check it. Or maybe pushing the `.idea` folder to github could be enough to replicate your config environment?

**Comment by born2net** [comment] 2017-02-08 19:02
sure thing, the config is super vanilla.
see below:
![snap](https://cloud.githubusercontent.com/assets/5090936/22752616/0d1f11b2-edee-11e6-9e75-d17e39e8ed71.PNG)



be happy to provide .idea if needed but its all very simple.

**Comment by zalmoxisus** [comment] 2017-02-08 19:16
1. I installed WebStorm's Chrome extension.
2. Added the settings like in your screenshot.
3. Clicked "debug" icon (as you can see in the video)
And still no exceptions.

![v3q9moluvy](https://cloud.githubusercontent.com/assets/7957859/22753115/9d397882-ee43-11e6-80e6-09c76b91f117.gif)

Unless I didn't miss anything, the resolution for you I guess is to build our extension in dev mode and debug it.

**Comment by born2net** [comment] 2017-02-08 19:19
first tx for the effort and GIFs.
no idea, I am using WebStorm 2017.1 EA
https://blog.jetbrains.com/webstorm/2016/12/webstorm-2017-1-early-access-preview/
not sure if related :/

**Comment by zalmoxisus** [comment] 2017-02-08 19:22
I'm redirected to `UserLogin` page not to `AutoLogin` in your video. Also I had to remove [this line](https://github.com/born2net/studioweb/blob/master/angular-cli.json#L34) because you don't have this file and it fails to build.  Maybe the source is different.

I'm using WebStorm 2016.2.4, but I doubt it makes any difference because the issue is related to its browser extension which is the same.

**Comment by born2net** [comment] 2017-02-08 19:24
tx will be fixing ```"./libs/bootstrap-timepicker/js/bootstrap-timepicker.min.js",``` on next submit
and if you click the [x] remember me, it should auto login you on the next reload

**Comment by zalmoxisus** [comment] 2017-02-08 19:31
OK, did it, but still no exceptions :)

I suggest to close this issue since it's not related to this repo in any way, and when you have some more details, please open a new issue on https://github.com/zalmoxisus/redux-devtools-extension. Some repo watchers may be annoyed with lots of notifications, while they are not using the extension (this repo is intended to use devtools without browser extension).

I [added the info in the README](https://github.com/gaearon/redux-devtools/commit/df1a4ea55515fdf0325cff33de5ab494208e94f1) to avoid the confusions in future.

Thanks you for the report anyway! And feel free to submit issues there.

**Closed by zalmoxisus** 2017-02-08 19:31 UTC

**Comment by born2net** [comment] 2017-02-08 19:33
thank you, I will continue this with WebStorm devs and see if I can resolve with them, tx again!

**Comment by jgfet** [comment] 2017-10-22 16:27
<img width="1235" alt="screen shot 2017-10-22 at 17 24 15" src="https://user-images.githubusercontent.com/28791001/31863987-fb81224a-b74d-11e7-87e1-d65cc9025413.png">
I suddenly got a similar thing running an Ionic3 project. (uses Angular 4 under covers too). Using Visual Studio Code - so not specific to an IDE.

**Comment by konijn** [comment] 2018-02-27 14:38
Got the same errors. My theory is that this is caused by breakpoints/syntax issues that happen before the <body> tag is loaded.

**Comment by Nagimesi** [comment] 2018-04-05 06:51
@konijn That's actually what caused it. I removed all breakpoints and no errors. Thank you.
