### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015-loose"

### ISSUE THREAD

**Issue by neoliang** [gaearon/redux-devtools#225] opened 2016-01-15 09:34 UTC
when i clone this repo , run the cmd in 'examples/flux-todomvc' as follow:
npm install
npm start

it raise an error.

error log:

ERROR in /Users/user/Downloads/redux-devtools-master/src/index.js
Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory "/Users/user/Downloads/redux-devtools-master"
    at OptionManager.mergePresets (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/user/Downloads/redux-devtools-master/examples/todomvc/node_modules/babel-loader/index.js:88:12)
 @ ./store/configureStore.dev.js 10:21-46

ERROR in ./components/Footer.js
Module build failed: SyntaxError: /Users/user/Downloads/redux-devtools-master/examples/todomvc/components/Footer.js: A semicolon is required after a class property (18:3)
  16 |     onClearMarked: PropTypes.func.isRequired,
  17 |     onShow: PropTypes.func.isRequired
> 18 |   }
     |    ^
  19 | 
  20 |   render() {
  21 |     return (

**Comment by gaearon** [comment] 2016-01-18 17:39
>Module build failed: SyntaxError: /Users/user/Downloads/redux-devtools-master/examples/todomvc/components/Footer.js: A semicolon is required after a class property (18:3)

This was fixed by #220.

>Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory "/Users/user/Downloads/redux-devtools-master"

I can't reproduce this. Try removing your `node_modules`, and running `npm install` both inside `redux-devtools` and `redux-devtools/examples/todomvc`. Then run `npm start`.

**Closed by gaearon** 2016-01-18 17:39 UTC

**Comment by julienvincent** [comment] 2016-02-25 10:35
`Module build failed: Error: Couldn't find preset "es2015-loose"` When attempting to use any of the devtool monitors. Installing `babel-preset-es2015-loose` results in the error: `Module build failed: ReferenceError: [BABEL]`

**Comment by julienvincent** [comment] 2016-02-25 10:49
Fixed. Was not excluding `node_modules` in webpack config

**Comment by ududsha** [comment] 2016-05-18 09:32
@gaearon @neoliang same happened to me and fixed.
`npm install` is not worked as expected. Most of the time I have to install dependencies (mostly dev dependencies) individually Eg: `npm install --save-dev babel-preset-es2015-loose` etc.
So you have to go to the root dir and install that unidentified packages as I mentioned above fixed my issues.
