### ISSUE TITLE
Support Redux v4

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [gaearon/redux-devtools#391] opened 2017-12-27 17:47 UTC
There are some breaking changes in Redux v4 that needs to be adressed here.

Using the `4.0.0-beta.1` release results in the following error:
```
Uncaught TypeError: Cannot read property 'state' of undefined
    at unliftState (instrument.js:579)
```
It is caused by [this change](https://github.com/reactjs/redux/commit/e54a7f22cd3e09c9903599ae430d25018cc5d48e) which appends a random string to the initial redux action type. But [here](https://github.com/zalmoxisus/redux-devtools-instrument/blob/0aa43f1aee8847ead13001aec5b5d54ce01c7e12/src/instrument.js#L508) in the store enhancher we assume that the inital action is called ```@@redux/INIT```

**Comment by ematipico** [comment] 2018-01-12 16:08
I can confirm, current version is not compatible with version 4.

**Comment by peleteiro** [comment] 2018-01-28 01:02
:+1:

**Comment by olee** [comment] 2018-01-28 12:25
I'm using this code snippet right now which makes it work again - at least a bit:
```
// tslint:disable:no-var-requires
const reduxModule = require('redux');
reduxModule.__DO_NOT_USE__ActionTypes.INIT = '@@redux/INIT';
reduxModule.__DO_NOT_USE__ActionTypes.REPLACE = '@@redux/REPLACE';
```

**Comment by tomspeak** [comment] 2018-02-01 20:04
@olee how are you using this? Does this go in your configure store?

**Comment by alvis** [comment] 2018-02-04 22:43
There is a PR solving this upstream problem at https://github.com/zalmoxisus/redux-devtools-instrument/pull/17. Now what we need is patience.

**Comment by zalmoxisus** [comment] 2018-02-21 13:01
Published `redux-devtools-instrument@1.8.3`. I think we don't need to increase `redux-devtools` version as well for this.

**Comment by ajcrites** [comment] 2018-02-21 15:19
Will this fix also apply to `redux-devtools-extension`? Is there anything we can do to use the latest changes?

**Comment by zalmoxisus** [comment] 2018-03-03 19:28
Should be fixed in `2.15.2`.

**Closed by zalmoxisus** 2018-03-03 19:28 UTC

**Comment by G-Rath** [comment] 2018-06-04 01:45
@zalmoxisus is there going to be a fix for `redux-devtools-extension`? 

It's been just under a year since last commit to that repo; has it been depreciated or moved?

**Comment by mmakrzem** [comment] 2019-01-18 14:50
@zalmoxisus I don't understand your comment.  I'm building an Electron application that uses Redux 4.  I have installed https://www.npmjs.com/package/electron-devtools-installer so that Electron's devTools has a Redux tab, but the tab remains empty.  To get it to populate, I needed to use redux-devtools-extension, but the version published on npm is only 2.13.7 which doesn't support redux 4.  If the published version of redux-devtools-extension gets updated in npm to the latest version (https://github.com/zalmoxisus/redux-devtools-extension/releases) then my problem would be solved I think.  See https://github.com/zalmoxisus/redux-devtools-extension/issues/632
