### ISSUE TITLE
Devtools block keyboard shortcuts 

### ISSUE THREAD

**Issue by teosz** [gaearon/redux-devtools#192] opened 2015-11-23 15:14 UTC
Devtools is blocking keyboard shortcuts like copy/paste (ctrl-c/ctrl-v), select all (ctrl-a), etc..

**Comment by DiogoDoreto** [comment] 2015-11-23 16:01
https://github.com/gaearon/redux-devtools-dock-monitor/pull/2

**Comment by gaearon** [comment] 2015-12-14 01:51
Duplicate of https://github.com/gaearon/redux-devtools-dock-monitor/pull/2.
This will be fixed in the final 3.0 release.

**Closed by gaearon** 2015-12-14 01:51 UTC

**Comment by gaearon** [comment] 2015-12-14 04:46
Fixed as of 3.0.
